spring:
  application:
    name: container-consumer
server:
  port: 2227
eureka:
  instance:
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
      
---
#spring:
#  profiles: docker
#  application:
#    name: user-service
#server:
#  port: 8080
#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registry-fetch-interval-seconds: 5
#    instance-info-replication-interval-seconds: 5
#    initial-instance-info-replication-interval-seconds: 5
#    serviceUrl:
#      defaultZone: http://192.168.99.100:8761/eureka/